package io.openems.edge.airconditioner.envicool;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( //
		name = "Air Conditioner Envicool", //
		description = "Implements the envicool air conditioner.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "airCon0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus brige.")
	String modbus_id() default "modbus0";

	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "";
	
	@AttributeDefinition(name = "Heating stop point temperature", description = "Heating stop point. Up to that temperature should be heated. Allowed range: -15 - 15 Celsius degree.")
	int heatingStopPointTemperature() default 15;
	
	@AttributeDefinition(name = "Heating hysteresis", description = "The hysteresis is applied to avoid continuous switching. Allowed range: 1 - 10 Celsius degree.")
	int heatingHysteresis() default 5;
	
	@AttributeDefinition(name = "Cooling stop point temperature", description = "Cooling stop point. Till that temperature should be cooled. Allowed range: 15 - 50 Celsius degree.")
	int coolingStopPointTemperature() default 23;

	@AttributeDefinition(name = "Cooling hysteresis", description = "The hysteresis is applied to avoid continuous switching. Allowed range: 1 - 10 Celsius degree.")
	int coolingHysteresis() default 3;
	
	@AttributeDefinition(name = "Dehumidification stop point", description = "Dehumidification stop point. Till that percentage, the humidity should be reduced. Allowed range: 40 - 90 %.")
	int dehumidificationStopPoint() default 60;
	
	@AttributeDefinition(name = "Dehumidification hysteresis", description = "The hysteresis is applied to avoid continuous switching. Allowed range: 1 - 30 %.")
	int dehumidificationHysteresis() default 10;
	
	String webconsole_configurationFactory_nameHint() default "Air Conditioner Envicool [{id}]";
}